"""
    RCSolution(x, vars)

Solution of a local rheological system: the solved values `x` paired with the
symbol naming the unknown each entry stands for (`x_keys` of the model).

An `RCSolution` is an `AbstractVector`, so it supports positional indexing and
iteration. Entries can also be retrieved by name, `sol[:τ]`, provided that
name labels a single entry.
"""
struct RCSolution{N, T} <: AbstractVector{T}
    x::SVector{N, T}
    vars::NTuple{N, Symbol}
end

RCSolution(c::AbstractCompositeModel, x::SVector) = RCSolution(x, x_keys(c))

Base.size(::RCSolution{N}) where {N} = (N,)
Base.IndexStyle(::Type{<:RCSolution}) = IndexLinear()
Base.@propagate_inbounds Base.getindex(sol::RCSolution, i::Int) = sol.x[i]

function Base.getindex(sol::RCSolution, k::Symbol)
    n = count(==(k), sol.vars)
    isone(n) || throw(ArgumentError("`:$k` labels $n entries of the solution; index those by position"))
    return sol.x[findfirst(==(k), sol.vars)]
end

function Base.show(io::IO, ::MIME"text/plain", sol::RCSolution)
    println(io, "RCSolution:")
    for (k, v) in zip(sol.vars, sol.x)
        println(io, "  ", k, " = ", v)
    end
    return nothing
end

"""
    solve(c::AbstractCompositeModel, x::SVector, vars, others; xnorm0=nothing,
          atol=1.0e-12, rtol=1.0e-12, itermax=1.0e4, verbose=false)

Solve the nonlinear residual system generated by composite model `c` with a
Newton-Raphson iteration and backtracking line search.

`x` is the current solver vector, usually from `initial_guess_x`. `vars`
contains prescribed differentiable inputs such as `ε` and `θ`; `others`
contains nondifferentiable auxiliary values such as `dt`, `τ0`, and `P0`.

For tensor-valued strain rates, the solver applies
`effective_strain_rate_correction` and solves in terms of the second invariant
of the corrected effective strain-rate tensor.

# Keywords
- `xnorm0`: normalization vector for residual norms. If `nothing`, ones are used.
- `atol`: absolute residual tolerance.
- `rtol`: relative residual tolerance against the initial residual.
- `itermax`: maximum Newton iterations.
- `verbose`: print the final iteration count, residual norm, and line-search step.

Returns an [`RCSolution`](@ref) pairing the solved vector with the names of the
unknowns.

Throws [`NonConvergenceError`](@ref) if the iteration ends without meeting
either tolerance, which includes the case of a residual that became `NaN`.
The solver also stops early when the Newton update leaves the iterate unchanged
at floating-point precision for three consecutive iterations. This prevents a
residual floor that cannot be represented by the selected numeric type from
consuming the full `itermax` budget.
"""
function solve(c::AbstractCompositeModel, x::SVector, vars0, others; xnorm0=nothing, atol::Float64 = 1.0e-12, rtol::Float64 = 1.0e-12, itermax = 1.0e4, verbose::Bool = false)
    # Pre-correct ONLY the direct elastic leafs of the outer composite
    # (simple Maxwell backstress).  Tensor arithmetic is used here so that
    # second_invariant(ε + τ0/(2G·dt)) is evaluated correctly even for
    # non-coaxial ε/τ0 pairs.
    # ParallelModel branch corrections are handled implicitly inside
    # compute_residual via subtract_elastic_correction, so they must NOT be
    # included here to avoid double-counting.
    ε_corr = _direct_leaf_elastic_correction(c, vars0.ε, others)
    εII    = second_invariant_value(vars0.ε .+ ε_corr)
    vars   = merge(vars0, (; ε = εII))

    # vars = merge((; ε = εII), vars0)
    xnorm = correct_xnorm(x, xnorm0)
    r     = compute_residual(c, x, vars, others)   # initial residual
    it = 0
    er = Inf
    er0 = mynorm(r, xnorm)

    nonneg = branch_strain_rate_mask(c)

    α = 1e0
    stagnant_iters = 0
    while er > atol && er > rtol * er0
        it += 1

        J = ForwardDiff.jacobian(y -> compute_residual(c, y, vars, others), x)
        Δx = backsolve(J, r)
        α = max_feasible_step(x, Δx, nonneg)
        if it > 1
            α = bt_line_search(Δx, x, c, vars, others, xnorm, er; α = α, ρ = 0.5, lstol = 0.95, α_min = 0.1)
        end
        x_next = x + α .* Δx

        # check convergence
        r = compute_residual(c, x_next, vars, others)
        er = mynorm(r, xnorm)

        # Once the update is below floating-point resolution, continuing the
        # Newton iteration cannot change either the iterate or its residual.
        # Also require the residual to be finite: non-finite residuals follow
        # the existing diagnostic path below. A decreasing but slow residual
        # must remain an iteration-limit failure, not a stagnation failure.
        if isfinite(er) && x_next == x
            stagnant_iters += 1
        else
            stagnant_iters = 0
        end
        x = x_next

        it > itermax && break

        if stagnant_iters ≥ 3
            throw(NonConvergenceError(it, er, x, :stagnation))
        end

        # ε_corr = effective_strain_rate_correction(c, vars0.ε, others.τ0, others)
        # ε_eff  = vars0.ε .+ ε_corr
        # εII    = second_invariant_value(ε_eff)
        # vars   = merge(vars0, (; ε = εII)) # this mames it type unstable; TODO

    end
    if verbose && it > 1
        println("Iterations: $it, Error: $er, α = $α")
    end
    # A NaN residual compares false against both tolerances and so exits the loop
    # by the same door as a converged one; `isfinite` is what separates them.
    isfinite(er) && (er ≤ atol || er ≤ rtol * er0) || throw(NonConvergenceError(it, er, x))
    return RCSolution(c, x)
end

solve(c::AbstractCompositeModel, sol::RCSolution, vars0, others; kwargs...) = solve(c, sol.x, vars0, others; kwargs...)
compute_residual(c, sol::RCSolution, vars, others) = compute_residual(c, sol.x, vars, others)

"""
    NonConvergenceError(iterations, residual, x)

Thrown by [`solve`](@ref) when the local Newton iteration ends without reaching
`atol` or `rtol`, including when the residual becomes `NaN` or `Inf`.

Fields hold the iteration count, the final normalized residual norm, the last
iterate, and a `reason` symbol (`:stagnation` or `:iteration_limit`), so a
caller catching this can distinguish a floating-point floor from an ordinary
iteration-limit failure and report or retry from the saved iterate.
"""
struct NonConvergenceError{T, X} <: Exception
    iterations::Int
    residual::T
    x::X
    reason::Symbol
end

NonConvergenceError(iterations, residual, x) = NonConvergenceError(iterations, residual, x, :iteration_limit)

function Base.showerror(io::IO, e::NonConvergenceError)
    print(io, "NonConvergenceError: the local Newton iteration did not converge")
    if e.reason === :stagnation
        print(io, " because the iterate/residual stagnated after $(e.iterations) iterations (before the iteration limit); the normalized residual norm is $(e.residual). ")
        print(io, "The requested tolerance is below the attainable floating-point resolution for this state.")
    elseif isfinite(e.residual)
        print(io, " within $(e.iterations) iterations; the normalized residual norm is $(e.residual). ")
        print(io, "Either the iteration limit is too low for this composite, or the tolerances are tighter than its conditioning allows.")
    else
        print(io, "; the normalized residual norm became $(e.residual) at iteration $(e.iterations). ")
        print(io, "This means an iterate reached a point where the composite is not evaluable — a zero strain rate in a parallel power-law branch is one such point, since its effective viscosity diverges there. ")
        print(io, "Check the initial guess.")
    end
    return print(io, "\nLast iterate: $(e.x)")
end

# Fraction of the distance to the boundary that a bounded step may cover. The
# iterate is held strictly inside x ≥ 0 rather than allowed to reach it: a
# branch strain rate of exactly zero is not just infeasible but singular, since
# d(ε^(1/n))/dε diverges there and the next Jacobian would be Inf.
const FRACTION_TO_BOUNDARY = 0.995

"""
    max_feasible_step(x, Δx, mask)

Return the largest step length in `(0, 1]` for which every entry of `x` marked
by `mask` stays strictly positive along `x + α * Δx`.

Entries that are not marked, that are already non-positive, or whose step is
non-negative impose no bound, so the step is only ever shortened where the
constraint is live.
"""
@generated function max_feasible_step(x::SVector{N}, Δx::SVector{N}, mask::SVector{N, Bool}) where {N}
    return quote
        @inline
        α = 1.0
        Base.@nexprs $N i -> begin
            xi = x[i]
            di = Δx[i]
            if mask[i] && di < 0 && xi > 0
                α = min(α, -FRACTION_TO_BOUNDARY * xi / di)
            end
        end
        return α
    end
end

"""
    branch_strain_rate_mask(c::AbstractCompositeModel)

Return an `SVector{N,Bool}` marking the entries of the solver vector of `c` that
hold the strain rate of a parallel branch.

These are second invariants and so non-negative, but the Newton iterate itself
is not: at low imposed strain rate it overshoots below zero, where a power law's
`ε^(1/n)` is undefined. The mask lets [`solve`](@ref) bound the step for exactly
these entries. Stress and multiplier unknowns are left unbounded — their
iterates are not the ones observed to leave the physical range, and bounding an
entry that starts at zero would block the first step.
"""
function branch_strain_rate_mask(c::AbstractCompositeModel)
    eqs = generate_equations(c)
    return SA[branch_strain_rate_mask(eqs)...]
end

@generated function branch_strain_rate_mask(eqs::NTuple{N, CompositeEquation}) where {N}
    return quote
        @inline
        Base.@ntuple $N i -> _is_branch_strain_rate(eqs[i].fn)
    end
end

# The unknown of a `compute_stress` equation is a parallel branch's strain rate.
@inline _is_branch_strain_rate(::F) where {F} = false
@inline _is_branch_strain_rate(::typeof(compute_stress)) = true

"""
    bt_line_search(Δx, x, composite, vars, others, xnorm, rnorm; α=1.0, ρ=0.5, lstol=0.9, α_min=1.0e-8)

Backtracking line search that repeatedly shrinks `α` by `ρ` until the residual
norm at `x + α * Δx` is at most `lstol` times the current residual norm. The
undamped full step (`α = 1.0`) is accepted outright whenever it does not
increase the residual, without requiring the stricter `lstol` reduction.
"""
function bt_line_search(Δx, x, composite, vars, others, xnorm, rnorm; α = 1.0, ρ = 0.5, lstol = 0.9, α_min = 1.0e-8)

    # Iterate unless step length becomes too small
    while α > α_min
        # Apply scaled update
        perturbed_x = @. x + α * Δx

        # Get updated residual
        perturbed_r = compute_residual(composite, perturbed_x, vars, others)
        perturbed_rnorm = mynorm(perturbed_r, xnorm)

        # Check whether residual is sufficiently reduced
        # for α = 1, only check if the residual decreases
        if perturbed_rnorm ≤ (α == 1.0 ? 1.0 : lstol) * rnorm
            break
        end

        # Bisect step length
        α *= ρ
    end

    return α
end

"""
    mynorm(x, y)

Return a normalized L1-like norm `sum(abs(x[i] / y[i]))`, skipping entries whose
normalization factor is zero.
"""
@generated function mynorm(x::SVector{N, T}, y::SVector{N}) where {N, T}
    return quote
        @inline
        v = zero(T)
        Base.@nexprs $N i -> begin
            xi = @inbounds x[i]
            yi = @inbounds y[i]
            v += !iszero(yi) * abs(xi / yi)
        end
        return v
    end
end

@inline backsolve(J::SVector{1}, r::SVector{1})   = SA[-r[1] * inv(J[1])]
@inline backsolve(J::SMatrix{1,1}, r::SVector{1}) = SA[-r[1] * inv(J[1])]
@inline backsolve(J, r) = J \ -r
