"""
    RCSolution(x::SVector, iterations, residual)

Solution of a local rheological system: the solved values `x`, the number of
Newton iterations [`solve`](@ref) needed, and the final normalized residual
norm.

An `RCSolution` is an `AbstractVector`, so it supports positional indexing and
iteration, and it can be passed straight back into `solve`. It holds numbers
only, and so is `isbits` and usable inside GPU kernels; [`inspect`](@ref)
describes what each entry stands for.
"""
struct RCSolution{N, T, R} <: AbstractVector{T}
    x::SVector{N, T}
    iterations::Int
    residual::R
end

@inline RCSolution(x::SVector{N, T}, iterations, residual) where {N, T} =
    RCSolution{N, T, typeof(residual)}(x, iterations, residual)

Base.size(::RCSolution{N}) where {N} = (N,)
Base.IndexStyle(::Type{<:RCSolution}) = IndexLinear()
Base.@propagate_inbounds Base.getindex(sol::RCSolution, i::Int) = sol.x[i]

function Base.show(io::IO, ::MIME"text/plain", sol::RCSolution)
    println(io, "RCSolution (iterations: ", sol.iterations, ", residual: ", sol.residual, ")")
    Base.print_array(io, sol.x)
    return nothing
end

"""
    jacobian(c, x, vars, others)

Build the local residual Jacobian with respect to the solver vector `x` using
the default ForwardDiff backend. The function is a small backend boundary for
future analytic or sparse implementations and currently preserves the
package's static local-system representation.
"""
@inline jacobian(c::AbstractCompositeModel, x::SVector, vars, others) =
    ForwardDiff.jacobian(y -> compute_residual(c, y, vars, others), x)

# Residual and Jacobian from a single ForwardDiff dual pass, via the supported
# `jacobian!`/DiffResults API. `solve` calls this once, for the residual and
# Jacobian it needs at its own starting point, to avoid the redundant primal
# residual evaluation implicit in computing that first Jacobian separately.
# Every later iteration already carries its residual from the previous line
# search, so it keeps calling `jacobian` alone: fusing there would recompute a
# residual `solve` already has, and the DiffResults extraction is not uniformly
# cheaper than the plain call when only the Jacobian is needed.
#
# `solve` (and hence this function) must itself stay differentiable, e.g. under
# `ForwardDiff.derivative(rate -> solve(c, x, (; ε = rate), others)[1], rate)`.
# There the residual's value type is an outer `Dual` even though `x` is plain
# `Float64`, so `DiffResults.JacobianResult(x)`/`JacobianResult(y, x)` are both
# unsafe here: their `StaticArray` methods type the Jacobian storage from `x`
# alone (see DiffResults.jl's `JacobianResult(y::StaticArray, x::StaticArray)`),
# which silently drops the outer dual and throws inside `jacobian!` once it
# tries to store one. The value and Jacobian slots are built directly instead,
# both typed from the residual's inferred output type `T`, which is what
# carries any outer dual layer through the Jacobian entries too. `T` is
# obtained by type inference (`Base.promote_op`), not by evaluating the
# residual, so this remains a single evaluation overall.
@inline function residual_and_jacobian(c::AbstractCompositeModel, x::SVector, vars, others)
    f = y -> compute_residual(c, y, vars, others)
    T = Base.promote_op(f, typeof(x))
    y_proto = zero(T)
    jacobian_proto = zeros(similar_type(T, Size(length(y_proto), length(x))))
    result = ForwardDiff.jacobian!(DiffResults.DiffResult(y_proto, (jacobian_proto,)), f, x)
    return DiffResults.value(result), DiffResults.jacobian(result)
end

"""
    solve(c::AbstractCompositeModel, x::SVector, vars, others; xnorm0=nothing,
          atol=1.0e-12, rtol=1.0e-12, itermax=1.0e4, verbose=false)

Solve the nonlinear residual system generated by composite model `c` with a
Newton-Raphson iteration and backtracking line search.

`x` is the current solver vector, usually from `initial_guess_x`. `vars`
contains prescribed differentiable inputs such as `ε` and `θ`; `others`
contains nondifferentiable auxiliary values such as `dt`, `τ0`, and `P0`.

For tensor-valued strain rates, the solver applies
`effective_strain_rate_correction` and solves in terms of the second invariant
of the corrected effective strain-rate tensor.

# Keywords
- `xnorm0`: normalization vector for residual norms. If `nothing`, ones are used.
- `atol`: absolute residual tolerance.
- `rtol`: relative residual tolerance against the initial residual.
- `itermax`: maximum Newton iterations.
- `verbose`: print the final iteration count, residual norm, and line-search step.

Returns an [`RCSolution`](@ref) holding the solved vector, the iteration count,
and the final residual norm. [`inspect`](@ref) describes its entries.

Throws [`NonConvergenceError`](@ref) if the iteration ends without meeting
either tolerance, which includes the case of a residual that became `NaN`.
The solver also stops early when the Newton update leaves the iterate unchanged
at floating-point precision for three consecutive iterations. This prevents a
residual floor that cannot be represented by the selected numeric type from
consuming the full `itermax` budget.
"""
function solve(c::AbstractCompositeModel, x::SVector, vars0, others; xnorm0 = nothing, atol::Float64 = 1.0e-12, rtol::Float64 = 1.0e-12, itermax = 1.0e4, verbose::Bool = false)
    # Pre-correct ONLY the direct elastic leafs of the outer composite
    # (simple Maxwell backstress).  Tensor arithmetic is used here so that
    # second_invariant(ε + τ0/(2G·dt)) is evaluated correctly even for
    # non-coaxial ε/τ0 pairs.
    # ParallelModel branch corrections are handled implicitly inside
    # compute_residual via subtract_elastic_correction, so they must NOT be
    # included here to avoid double-counting.
    ε_corr = _direct_leaf_elastic_correction(c, vars0.ε, others)
    εII = second_invariant_value(vars0.ε .+ ε_corr)
    vars = merge(vars0, (; ε = εII))

    # vars = merge((; ε = εII), vars0)
    xnorm = correct_xnorm(x, xnorm0)
    # Initial residual and its Jacobian, fused: the loop below always runs at
    # least one iteration (`er` starts at `Inf`, not `er0`), so this Jacobian
    # is never wasted the way a preemptively computed next-iterate Jacobian
    # could be.
    r, J = residual_and_jacobian(c, x, vars, others)
    it = 0
    er0 = mynorm(r, xnorm)
    # `oftype` keeps the residual a single type across the loop, so that the
    # value stored in the returned `RCSolution` is inferrable.
    er = oftype(er0, Inf)

    nonneg = branch_strain_rate_mask(c)

    α = 1.0e0
    stagnant_iters = 0
    while er > atol && er > rtol * er0
        it += 1

        # The first iteration's Jacobian was already produced above, fused
        # with the initial residual; later iterations recompute it here since
        # their residual instead comes from the previous line search.
        it > 1 && (J = jacobian(c, x, vars, others))
        Δx = backsolve(J, r)
        α = max_feasible_step(x, Δx, nonneg)
        α, x_next, r, er = _bt_line_search_result(
            Δx, x, c, vars, others, xnorm, er;
            α = α, ρ = 0.5, lstol = 0.95, α_min = 0.1
        )

        # Once the update is below floating-point resolution, continuing the
        # Newton iteration cannot change either the iterate or its residual.
        # Also require the residual to be finite: non-finite residuals follow
        # the existing diagnostic path below. A decreasing but slow residual
        # must remain an iteration-limit failure, not a stagnation failure.
        if isfinite(er) && x_next == x
            stagnant_iters += 1
        else
            stagnant_iters = 0
        end
        x = x_next

        it > itermax && break

        if stagnant_iters ≥ 3
            throw(NonConvergenceError(it, er, x, :stagnation))
        end

        # ε_corr = effective_strain_rate_correction(c, vars0.ε, others.τ0, others)
        # ε_eff  = vars0.ε .+ ε_corr
        # εII    = second_invariant_value(ε_eff)
        # vars   = merge(vars0, (; ε = εII)) # this mames it type unstable; TODO

    end
    if verbose && it > 1
        println("Iterations: $it, Error: $er, α = $α")
    end
    # A NaN residual compares false against both tolerances and so exits the loop
    # by the same door as a converged one; `isfinite` is what separates them.
    isfinite(er) && (er ≤ atol || er ≤ rtol * er0) || throw(NonConvergenceError(it, er, x))
    return RCSolution(x, it, er)
end

solve(c::AbstractCompositeModel, sol::RCSolution, vars0, others; kwargs...) = solve(c, sol.x, vars0, others; kwargs...)

"""
    solve_batch(c, xs, vars, others; kwargs...)

Solve a statically sized batch of independent local systems. The tuple-based
API keeps the batch result concrete and is the reference path for later CPU or
GPU kernels.
"""
function solve_batch(c::AbstractCompositeModel, xs::NTuple{N, SVector}, vars::NTuple{N}, others::NTuple{N}; kwargs...) where {N}
    return ntuple(i -> solve(c, xs[i], vars[i], others[i]; kwargs...), Val(N))
end

"""
    solve_with_retries(c, x, vars, others; max_retries=2,
                       tolerance_factor=10, kwargs...)

Retry a failed local solve from its last iterate with progressively relaxed
tolerances. This orchestration is host-side; the ordinary `solve` path remains
deterministic and device-friendly.
"""
function solve_with_retries(
        c::AbstractCompositeModel, x::SVector, vars, others;
        max_retries::Integer = 2,
        tolerance_factor = 10,
        atol = 1.0e-12,
        rtol = 1.0e-12,
        kwargs...
    )
    max_retries ≥ 0 || throw(ArgumentError("max_retries must be non-negative"))
    tolerance_factor ≥ 1 || throw(ArgumentError("tolerance_factor must be at least one"))
    current_x = x
    current_atol = atol
    current_rtol = rtol
    for attempt in 0:max_retries
        try
            return solve(
                c, current_x, vars, others;
                atol = current_atol, rtol = current_rtol, kwargs...
            )
        catch err
            err isa NonConvergenceError || rethrow()
            attempt == max_retries && rethrow()
            current_x = err.x
            current_atol *= tolerance_factor
            current_rtol *= tolerance_factor
        end
    end
    error("unreachable")
end
compute_residual(c, sol::RCSolution, vars, others) = compute_residual(c, sol.x, vars, others)

"""
    NonConvergenceError(iterations, residual, x)

Thrown by [`solve`](@ref) when the local Newton iteration ends without reaching
`atol` or `rtol`, including when the residual becomes `NaN` or `Inf`.

Fields hold the iteration count, the final normalized residual norm, the last
iterate, and a `reason` symbol (`:stagnation` or `:iteration_limit`), so a
caller catching this can distinguish a floating-point floor from an ordinary
iteration-limit failure and report or retry from the saved iterate.
"""
struct NonConvergenceError{T, X} <: Exception
    iterations::Int
    residual::T
    x::X
    reason::Symbol
end

NonConvergenceError(iterations, residual, x) = NonConvergenceError(iterations, residual, x, :iteration_limit)

function Base.showerror(io::IO, e::NonConvergenceError)
    print(io, "NonConvergenceError: the local Newton iteration did not converge")
    if e.reason === :stagnation
        print(io, " because the iterate/residual stagnated after $(e.iterations) iterations (before the iteration limit); the normalized residual norm is $(e.residual). ")
        print(io, "The requested tolerance is below the attainable floating-point resolution for this state.")
    elseif isfinite(e.residual)
        print(io, " within $(e.iterations) iterations; the normalized residual norm is $(e.residual). ")
        print(io, "Either the iteration limit is too low for this composite, or the tolerances are tighter than its conditioning allows.")
    else
        print(io, "; the normalized residual norm became $(e.residual) at iteration $(e.iterations). ")
        print(io, "This means an iterate reached a point where the composite is not evaluable — a zero strain rate in a parallel power-law branch is one such point, since its effective viscosity diverges there. ")
        print(io, "Check the initial guess.")
    end
    return print(io, "\nLast iterate: $(e.x)")
end

# Fraction of the distance to the boundary that a bounded step may cover. The
# iterate is held strictly inside x ≥ 0 rather than allowed to reach it: a
# branch strain rate of exactly zero is not just infeasible but singular, since
# d(ε^(1/n))/dε diverges there and the next Jacobian would be Inf.
const FRACTION_TO_BOUNDARY = 0.995

"""
    max_feasible_step(x, Δx, mask)

Return the largest step length in `(0, 1]` for which every entry of `x` marked
by `mask` stays strictly positive along `x + α * Δx`.

Entries that are not marked, that are already non-positive, or whose step is
non-negative impose no bound, so the step is only ever shortened where the
constraint is live.
"""
@generated function max_feasible_step(x::SVector{N}, Δx::SVector{N}, mask::SVector{N, Bool}) where {N}
    return quote
        @inline
        α = 1.0
        Base.@nexprs $N i -> begin
            xi = x[i]
            di = Δx[i]
            if mask[i] && di < 0 && xi > 0
                α = min(α, -FRACTION_TO_BOUNDARY * xi / di)
            end
        end
        return α
    end
end

"""
    branch_strain_rate_mask(c::AbstractCompositeModel)

Return an `SVector{N,Bool}` marking the entries of the solver vector of `c` that
hold the strain rate of a parallel branch.

These are second invariants and so non-negative, but the Newton iterate itself
is not: at low imposed strain rate it overshoots below zero, where a power law's
`ε^(1/n)` is undefined. The mask lets [`solve`](@ref) bound the step for exactly
these entries. Stress and multiplier unknowns are left unbounded — their
iterates are not the ones observed to leave the physical range, and bounding an
entry that starts at zero would block the first step.
"""
function branch_strain_rate_mask(c::AbstractCompositeModel)
    eqs = generate_equations(c)
    return SA[branch_strain_rate_mask(eqs)...]
end

@inline branch_strain_rate_mask(eqs::NTuple{N, CompositeEquation}) where {N} =
    maptuple(eq -> _is_branch_strain_rate(eq.fn), eqs)

# The unknown of a `compute_stress` equation is a parallel branch's strain rate.
@inline _is_branch_strain_rate(::F) where {F} = false
@inline _is_branch_strain_rate(::typeof(compute_stress)) = true

"""
    bt_line_search(Δx, x, composite, vars, others, xnorm, rnorm; α=1.0, ρ=0.5, lstol=0.9, α_min=1.0e-8)

Backtracking line search that repeatedly shrinks `α` by `ρ` until the residual
norm at `x + α * Δx` is at most `lstol` times the current residual norm. The
initial feasible step is accepted whenever it does not increase the residual;
backtracked steps require the stricter `lstol` reduction. If no trial passes,
the best finite trial is returned.
"""
function bt_line_search(Δx, x, composite, vars, others, xnorm, rnorm; α = 1.0, ρ = 0.5, lstol = 0.9, α_min = 1.0e-8)
    # Preserve the step-only helper's behavior when there are no trials.
    α >= α_min || return α
    return first(_bt_line_search_result(Δx, x, composite, vars, others, xnorm, rnorm; α, ρ, lstol, α_min))
end

# Return the chosen point and residual as well as its step length. The initial
# point is also the fallback if no finite trial exists or the feasible step is
# below α_min; solve previously evaluated that point after the step-only search.
@inline function _bt_line_search_result(Δx, x, composite, vars, others, xnorm, rnorm; α = 1.0, ρ = 0.5, lstol = 0.9, α_min = 1.0e-8)
    α_initial = α
    best_rnorm = Inf
    perturbed_x = x + α .* Δx
    perturbed_r = compute_residual(composite, perturbed_x, vars, others)
    perturbed_rnorm = mynorm(perturbed_r, xnorm)
    best = (α, perturbed_x, perturbed_r, perturbed_rnorm)

    while α ≥ α_min
        if isfinite(perturbed_rnorm) && perturbed_rnorm < best_rnorm
            best = (α, perturbed_x, perturbed_r, perturbed_rnorm)
            best_rnorm = perturbed_rnorm
        end

        # The first feasible trial may be limited by non-negativity, so do not
        # demand artificial decrease from a step that merely avoids growth.
        target = α == α_initial ? 1.0 : lstol
        if isfinite(perturbed_rnorm) && perturbed_rnorm ≤ target * rnorm
            return (α, perturbed_x, perturbed_r, perturbed_rnorm)
        end

        # Bisect step length
        α *= ρ
        α ≥ α_min || break
        perturbed_x = x + α .* Δx
        perturbed_r = compute_residual(composite, perturbed_x, vars, others)
        perturbed_rnorm = mynorm(perturbed_r, xnorm)
    end

    return best
end

"""
    mynorm(x, y)

Return a normalized L1-like norm `sum(abs(x[i] / y[i]))`, skipping entries whose
normalization factor is zero.
"""
@generated function mynorm(x::SVector{N, T}, y::SVector{N}) where {N, T}
    return quote
        @inline
        v = zero(T)
        Base.@nexprs $N i -> begin
            xi = @inbounds x[i]
            yi = @inbounds y[i]
            v += !iszero(yi) * abs(xi / yi)
        end
        return v
    end
end

@inline backsolve(J::SVector{1}, r::SVector{1}) = SA[-r[1] * inv(J[1])]
@inline backsolve(J::SMatrix{1, 1}, r::SVector{1}) = SA[-r[1] * inv(J[1])]
@inline backsolve(J, r) = J \ -r
