"""
    RCSolution(x::SVector, iterations, residual, jacobian = nothing)

Solution of a local rheological system: the solved values `x`, the number of
Newton iterations [`solve`](@ref) needed, the final normalized residual norm,
and the residual Jacobian at the converged iterate.

An `RCSolution` is an `AbstractVector`, so it supports positional indexing and
iteration, and it can be passed straight back into `solve`. It holds numbers
only, and so is `isbits` and usable inside GPU kernels; [`inspect`](@ref)
describes what each entry stands for.

`jacobian` is `∂r/∂x` evaluated at the returned `x`, which is what an
implicit-function-theorem tangent needs. `solve` fills it in; it is `nothing`
for an `RCSolution` built by hand without one.

Note that this is NOT one of the Jacobians the Newton iteration formed: those
are taken at the iterates *before* the last update, and the tangent needs the
one at the converged point. Computing it therefore costs exactly one extra
Jacobian evaluation per `solve`. Measured on a 3-unknown visco-elasto-plastic
cap composite at a plastic point taking 2 Newton iterations (`julia -t 1`, via
GeoTech.jl's `perf/rc_bench.jl`, median of five runs): about 0.60 µs -> 0.72 µs
per call, with allocations unchanged at 0 bytes. That is cheaper than the
caller recomputing the same Jacobian, which is what callers building consistent
tangents did before.
"""
struct RCSolution{N, T, R, J} <: AbstractVector{T}
    x::SVector{N, T}
    iterations::Int
    residual::R
    jacobian::J
end

@inline RCSolution(x::SVector{N, T}, iterations, residual, jacobian = nothing) where {N, T} =
    RCSolution{N, T, typeof(residual), typeof(jacobian)}(x, iterations, residual, jacobian)

Base.size(::RCSolution{N}) where {N} = (N,)
Base.IndexStyle(::Type{<:RCSolution}) = IndexLinear()
Base.@propagate_inbounds Base.getindex(sol::RCSolution, i::Int) = sol.x[i]

function Base.show(io::IO, ::MIME"text/plain", sol::RCSolution)
    println(io, "RCSolution (iterations: ", sol.iterations, ", residual: ", sol.residual, ")")
    Base.print_array(io, sol.x)
    return nothing
end

"""
    jacobian(c, x, vars, others)

Build the local residual Jacobian with respect to the solver vector `x` using
the default ForwardDiff backend. The function is a small backend boundary for
future analytic or sparse implementations and currently preserves the
package's static local-system representation.
"""
@inline jacobian(c::AbstractCompositeModel, x::SVector, vars, others) =
    ForwardDiff.jacobian(y -> compute_residual(c, y, vars, others), x)

"""
    solve(c::AbstractCompositeModel, x::SVector, vars, others; xnorm0=nothing,
          atol=1.0e-12, rtol=1.0e-12, itermax=1.0e4, verbose=false)

Solve the nonlinear residual system generated by composite model `c` with a
Newton-Raphson iteration and backtracking line search.

`x` is the current solver vector, usually from `initial_guess_x`. `vars`
contains prescribed differentiable inputs such as `ε` and `θ`; `others`
contains nondifferentiable auxiliary values such as `dt`, `τ0`, and `P0`.

For tensor-valued strain rates, the solver applies
`effective_strain_rate_correction` and solves in terms of the second invariant
of the corrected effective strain-rate tensor.

# Keywords
- `xnorm0`: normalization vector for residual norms. If `nothing`, ones are used.
- `atol`: absolute residual tolerance.
- `rtol`: relative residual tolerance against the initial residual.
- `itermax`: maximum Newton iterations.
- `verbose`: print the final iteration count, residual norm, and line-search step.

Returns an [`RCSolution`](@ref) holding the solved vector, the iteration count,
the final residual norm, and the residual Jacobian at the converged iterate.
[`inspect`](@ref) describes its entries.

The initial guess `x` can be seeded through `initial_guess_x`'s `args.x0`; see
[`initial_guess_x`](@ref).

Throws [`NonConvergenceError`](@ref) if the iteration ends without meeting
either tolerance, which includes the case of a residual that became `NaN`.
The solver also stops early when the Newton update leaves the iterate unchanged
at floating-point precision for three consecutive iterations. This prevents a
residual floor that cannot be represented by the selected numeric type from
consuming the full `itermax` budget.
"""
function solve(c::AbstractCompositeModel, x::SVector, vars0, others; xnorm0 = nothing, atol::Float64 = 1.0e-12, rtol::Float64 = 1.0e-12, itermax = 1.0e4, verbose::Bool = false)
    # Pre-correct ONLY the direct elastic leafs of the outer composite
    # (simple Maxwell backstress).  Tensor arithmetic is used here so that
    # second_invariant(ε + τ0/(2G·dt)) is evaluated correctly even for
    # non-coaxial ε/τ0 pairs.
    # ParallelModel branch corrections are handled implicitly inside
    # compute_residual via subtract_elastic_correction, so they must NOT be
    # included here to avoid double-counting.
    ε_corr = _direct_leaf_elastic_correction(c, vars0.ε, others)
    εII = second_invariant_value(vars0.ε .+ ε_corr)
    vars = merge(vars0, (; ε = εII))

    # vars = merge((; ε = εII), vars0)
    xnorm = correct_xnorm(x, xnorm0)
    r = compute_residual(c, x, vars, others)   # initial residual
    it = 0
    er0 = mynorm(r, xnorm)
    # `oftype` keeps the residual a single type across the loop, so that the
    # value stored in the returned `RCSolution` is inferrable.
    er = oftype(er0, Inf)

    nonneg = branch_strain_rate_mask(c)

    α = 1.0e0
    stagnant_iters = 0
    while er > atol && er > rtol * er0
        it += 1

        J = jacobian(c, x, vars, others)
        Δx = backsolve(J, r)
        α = max_feasible_step(x, Δx, nonneg)
        # The search already evaluated the residual at the step it accepts, so
        # take its iterate and residual rather than repeating the evaluation.
        α, x_next, r = bt_line_search(
            Δx, x, c, vars, others, xnorm, er;
            α = α, ρ = 0.5, lstol = 0.95, α_min = 0.1
        )

        # check convergence
        er = mynorm(r, xnorm)

        # Once the update is below floating-point resolution, continuing the
        # Newton iteration cannot change either the iterate or its residual.
        # Also require the residual to be finite: non-finite residuals follow
        # the existing diagnostic path below. A decreasing but slow residual
        # must remain an iteration-limit failure, not a stagnation failure.
        if isfinite(er) && x_next == x
            stagnant_iters += 1
        else
            stagnant_iters = 0
        end
        x = x_next

        it > itermax && break

        if stagnant_iters ≥ 3
            throw(NonConvergenceError(it, er, x, :stagnation))
        end

        # ε_corr = effective_strain_rate_correction(c, vars0.ε, others.τ0, others)
        # ε_eff  = vars0.ε .+ ε_corr
        # εII    = second_invariant_value(ε_eff)
        # vars   = merge(vars0, (; ε = εII)) # this mames it type unstable; TODO

    end
    if verbose && it > 1
        println("Iterations: $it, Error: $er, α = $α")
    end
    # A NaN residual compares false against both tolerances and so exits the loop
    # by the same door as a converged one; `isfinite` is what separates them.
    isfinite(er) && (er ≤ atol || er ≤ rtol * er0) || throw(NonConvergenceError(it, er, x))
    # The Jacobian at the CONVERGED x, which is one step beyond every Jacobian
    # the loop formed (those are taken before the update that produced `x`).
    # Callers building implicit-function-theorem tangents need exactly this one,
    # so returning it here saves them a recomputation; it costs one extra
    # Jacobian evaluation per solve.
    return RCSolution(x, it, er, jacobian(c, x, vars, others))
end

solve(c::AbstractCompositeModel, sol::RCSolution, vars0, others; kwargs...) = solve(c, sol.x, vars0, others; kwargs...)

"""
    solve_batch(c, xs, vars, others; kwargs...)

Solve a statically sized batch of independent local systems. The tuple-based
API keeps the batch result concrete and is the reference path for later CPU or
GPU kernels.
"""
function solve_batch(c::AbstractCompositeModel, xs::NTuple{N, SVector}, vars::NTuple{N}, others::NTuple{N}; kwargs...) where {N}
    return ntuple(i -> solve(c, xs[i], vars[i], others[i]; kwargs...), Val(N))
end

"""
    solve_with_retries(c, x, vars, others; max_retries=2,
                       tolerance_factor=10, kwargs...)

Retry a failed local solve from its last iterate with progressively relaxed
tolerances. This orchestration is host-side; the ordinary `solve` path remains
deterministic and device-friendly.
"""
function solve_with_retries(
        c::AbstractCompositeModel, x::SVector, vars, others;
        max_retries::Integer = 2,
        tolerance_factor = 10,
        atol = 1.0e-12,
        rtol = 1.0e-12,
        kwargs...
    )
    max_retries ≥ 0 || throw(ArgumentError("max_retries must be non-negative"))
    tolerance_factor ≥ 1 || throw(ArgumentError("tolerance_factor must be at least one"))
    current_x = x
    current_atol = atol
    current_rtol = rtol
    for attempt in 0:max_retries
        try
            return solve(
                c, current_x, vars, others;
                atol = current_atol, rtol = current_rtol, kwargs...
            )
        catch err
            err isa NonConvergenceError || rethrow()
            attempt == max_retries && rethrow()
            current_x = err.x
            current_atol *= tolerance_factor
            current_rtol *= tolerance_factor
        end
    end
    error("unreachable")
end
compute_residual(c, sol::RCSolution, vars, others) = compute_residual(c, sol.x, vars, others)

"""
    NonConvergenceError(iterations, residual, x)

Thrown by [`solve`](@ref) when the local Newton iteration ends without reaching
`atol` or `rtol`, including when the residual becomes `NaN` or `Inf`.

Fields hold the iteration count, the final normalized residual norm, the last
iterate, and a `reason` symbol (`:stagnation` or `:iteration_limit`), so a
caller catching this can distinguish a floating-point floor from an ordinary
iteration-limit failure and report or retry from the saved iterate.
"""
struct NonConvergenceError{T, X} <: Exception
    iterations::Int
    residual::T
    x::X
    reason::Symbol
end

NonConvergenceError(iterations, residual, x) = NonConvergenceError(iterations, residual, x, :iteration_limit)

function Base.showerror(io::IO, e::NonConvergenceError)
    print(io, "NonConvergenceError: the local Newton iteration did not converge")
    if e.reason === :stagnation
        print(io, " because the iterate/residual stagnated after $(e.iterations) iterations (before the iteration limit); the normalized residual norm is $(e.residual). ")
        print(io, "The requested tolerance is below the attainable floating-point resolution for this state.")
    elseif isfinite(e.residual)
        print(io, " within $(e.iterations) iterations; the normalized residual norm is $(e.residual). ")
        print(io, "Either the iteration limit is too low for this composite, or the tolerances are tighter than its conditioning allows.")
    else
        print(io, "; the normalized residual norm became $(e.residual) at iteration $(e.iterations). ")
        print(io, "This means an iterate reached a point where the composite is not evaluable — a zero strain rate in a parallel power-law branch is one such point, since its effective viscosity diverges there. ")
        print(io, "Check the initial guess.")
    end
    return print(io, "\nLast iterate: $(e.x)")
end

# Fraction of the distance to the boundary that a bounded step may cover. The
# iterate is held strictly inside x ≥ 0 rather than allowed to reach it: a
# branch strain rate of exactly zero is not just infeasible but singular, since
# d(ε^(1/n))/dε diverges there and the next Jacobian would be Inf.
const FRACTION_TO_BOUNDARY = 0.995

"""
    max_feasible_step(x, Δx, mask)

Return the largest step length in `(0, 1]` for which every entry of `x` marked
by `mask` stays strictly positive along `x + α * Δx`.

Entries that are not marked, that are already non-positive, or whose step is
non-negative impose no bound, so the step is only ever shortened where the
constraint is live.
"""
@generated function max_feasible_step(x::SVector{N}, Δx::SVector{N}, mask::SVector{N, Bool}) where {N}
    return quote
        @inline
        α = 1.0
        Base.@nexprs $N i -> begin
            xi = x[i]
            di = Δx[i]
            if mask[i] && di < 0 && xi > 0
                α = min(α, -FRACTION_TO_BOUNDARY * xi / di)
            end
        end
        return α
    end
end

"""
    branch_strain_rate_mask(c::AbstractCompositeModel)

Return an `SVector{N,Bool}` marking the entries of the solver vector of `c` that
hold the strain rate of a parallel branch.

These are second invariants and so non-negative, but the Newton iterate itself
is not: at low imposed strain rate it overshoots below zero, where a power law's
`ε^(1/n)` is undefined. The mask lets [`solve`](@ref) bound the step for exactly
these entries. Stress and multiplier unknowns are left unbounded — their
iterates are not the ones observed to leave the physical range, and bounding an
entry that starts at zero would block the first step.
"""
function branch_strain_rate_mask(c::AbstractCompositeModel)
    eqs = generate_equations(c)
    return SA[branch_strain_rate_mask(eqs)...]
end

@inline branch_strain_rate_mask(eqs::NTuple{N, CompositeEquation}) where {N} =
    maptuple(eq -> _is_branch_strain_rate(eq.fn), eqs)

# The unknown of a `compute_stress` equation is a parallel branch's strain rate.
@inline _is_branch_strain_rate(::F) where {F} = false
@inline _is_branch_strain_rate(::typeof(compute_stress)) = true

"""
    bt_line_search(Δx, x, composite, vars, others, xnorm, rnorm; α=1.0, ρ=0.5, lstol=0.9, α_min=1.0e-8)

Backtracking line search that repeatedly shrinks `α` by `ρ` until the residual
norm at `x + α * Δx` is at most `lstol` times the current residual norm. The
initial feasible step is accepted whenever it does not increase the residual;
backtracked steps require the stricter `lstol` reduction. If no trial passes,
the best finite trial is returned.

Returns `(α, x_next, r)`: the accepted step length, the iterate it produces,
and the residual there. The iterate and residual are the ones the search
actually evaluated at the *returned* `α`, so [`solve`](@ref) can use them
directly instead of recomputing `compute_residual` at a point the search has
already visited.

Carrying `x_next` and `r` out rather than only `α` is what makes the reuse
correct. The accepted `α` is not always the last one tried: when no trial meets
its target the search returns `best_α`, which may come from any earlier trial,
so the most recently computed residual can belong to a different step length.
Keeping the triple together cannot make that mistake.
"""
function bt_line_search(Δx, x, composite, vars, others, xnorm, rnorm; α = 1.0, ρ = 0.5, lstol = 0.9, α_min = 1.0e-8)

    α_initial = α
    best_α = α
    best_rnorm = Inf
    # The iterate and residual belonging to `best_α`, kept in step with it.
    #
    # `best_α` is seeded to `α_initial`, NOT to zero, so when no trial has a
    # finite residual the search still returns a moving step; the iterate is
    # seeded to the point that same `α_initial` produces. Seeding `best_x = x`
    # instead would make the fall-through return the current point unchanged,
    # `solve` would then see `x_next == x`, and its stagnation guard would abort
    # a solve that previously made progress — turning the 469-step
    # yield-crossing accumulation of `test_solver_convergence.jl` from converged
    # into a stagnation failure at a residual of ~1.
    #
    # The residual seed is what the loop's first pass recomputes at the same
    # point. Keeping it means the fall-through and the `α < α_min` entry case
    # both report the residual really found there, which is what `solve`'s
    # NaN/Inf diagnostics read. The line search therefore still performs one
    # evaluation per trial plus this seed, and what `solve` saves is its own
    # post-loop `compute_residual`, which used to re-evaluate a point the search
    # had already visited.
    best_x = @. x + α * Δx
    best_r = compute_residual(composite, best_x, vars, others)

    while α ≥ α_min
        # Apply scaled update
        perturbed_x = @. x + α * Δx

        # Get updated residual
        perturbed_r = compute_residual(composite, perturbed_x, vars, others)
        perturbed_rnorm = mynorm(perturbed_r, xnorm)

        if isfinite(perturbed_rnorm) && perturbed_rnorm < best_rnorm
            best_α, best_rnorm = α, perturbed_rnorm
            best_x, best_r = perturbed_x, perturbed_r
        end

        # The first feasible trial may be limited by non-negativity, so do not
        # demand artificial decrease from a step that merely avoids growth.
        target = α == α_initial ? 1.0 : lstol
        if isfinite(perturbed_rnorm) && perturbed_rnorm ≤ target * rnorm
            return α, perturbed_x, perturbed_r
        end

        # Bisect step length
        α *= ρ
    end

    return best_α, best_x, best_r
end

"""
    mynorm(x, y)

Return a normalized L1-like norm `sum(abs(x[i] / y[i]))`.

A zero normalization factor measures its row unscaled (`abs(x[i])`) instead of
dropping it. Dropping was the previous behaviour and made the norm blind: a row
with a zero factor contributed nothing however large its residual, so a state
whose characteristic scale vanishes — an undeformed point, where
`char_ε = εII + |θ| = 0` — could report a residual of exactly `0.0` while the
true residual was far above `atol`. [`normalisation_x`](@ref) now floors the
characteristic scales, so zero factors should no longer arise from that path;
this keeps a hand-built `xnorm0` containing zeros honest as well.
"""
@generated function mynorm(x::SVector{N, T}, y::SVector{N}) where {N, T}
    return quote
        @inline
        v = zero(T)
        Base.@nexprs $N i -> begin
            xi = @inbounds x[i]
            yi = @inbounds y[i]
            v += iszero(yi) ? abs(xi) : abs(xi / yi)
        end
        return v
    end
end

@inline backsolve(J::SVector{1}, r::SVector{1}) = SA[-r[1] * inv(J[1])]
@inline backsolve(J::SMatrix{1, 1}, r::SVector{1}) = SA[-r[1] * inv(J[1])]
@inline backsolve(J, r) = J \ -r
